on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install surrealDb
        run: curl -sSf https://install.surrealdb.com | sh
      - name: Start database
        run: surreal start --log trace --user root --pass root memory